### ISSUE TITLE
F0 result is different from VAMP plugin

### ISSUE THREAD

**Issue by EliosMolina** [xstreck1/LibPyin#1]
Hi! Nice job here. I would like to comment that I get different results if using sonic-annotator with VAMP plugin. I'm working on it here:
https://github.com/EliosMolina/LibPyin

If you think there is something I should take into account to solve it, please let me know. Thanks.

**Comment by EliosMolina** [comment]
I've solved the problem in https://github.com/EliosMolina/LibPyin 

pYIN produces a frame-wise output (the one you provide), but also a smoothed contour. The latter is much more powerful and it has a good behavior even in noisy environments (http://www.terasoft.com.tw/conf/ismir2014/proceedings/T051_147_Paper.pdf)

**Comment by xstreck1** [comment]
Hi,

as you suggested, there is no self-correction in the algorithm, thus you can easily get an overtone of the actual tone (in a higher or a lower octave), which seems to be the case in your graph---I can't read off the values specifically, but it seems to have peaks that differ from the curve by powers of 2, i.e. overtones. 

The library just takes the highest estimated probability, however if that is a problem, it would make sense to add auto-correlation on the top of the pYIN result: https://en.wikipedia.org/wiki/Autocorrelation
