### ISSUE TITLE
Have to call .feed twice to see results

### ISSUE THREAD

**Issue by mavavilj** [xstreck1/LibPyin#11]
I'm using https://github.com/xstreck1/LibPyin/blob/5a27943f5454d19b0b0f9a85457c153c04303a44/main.cpp with non-essential modifications.

I notice that the line:

https://github.com/xstreck1/LibPyin/blob/5a27943f5454d19b0b0f9a85457c153c04303a44/main.cpp#L30

returns 0 elements when it's called once and returns the expected elements when called a second time.

I've checked that the input is okay.

But it sounds as if the thing fails to initialize or something.

**Comment by mavavilj** [comment]
When it calls the first time, this happens:

![Screenshot from 2023-03-08 14-35-23](https://user-images.githubusercontent.com/1913544/223715298-df52232d-c8c7-492d-a26b-9662d4291f4c.png)

But there are no pitches:

![Screenshot from 2023-03-08 14-38-43](https://user-images.githubusercontent.com/1913544/223715588-0c609777-b0e6-463d-8b58-5a203287478d.png)

**Comment by mavavilj** [comment]
It seems related to sample size and block size:
```
        int SAMPLE_COUNT = 2048;
        int BLOCK_SIZE = 1024;
```

does work and returns two pitches.

```
        int SAMPLE_COUNT = 2048;
        int BLOCK_SIZE = 2048;
```

returns 0 pitches.

**Comment by xstreck1** [comment]
Last sample was not considered, I changed the loop condition 557fcbcb6c.
