### ISSUE TITLE
Over Nyquist pitches with noisy sample

### ISSUE THREAD

**Issue by mavavilj** [xstreck1/LibPyin#13]
I am feeding the library a sample that's supposed to have a ~500 Hz tone, but it also has a lot of noise over it. The file is 44100 Hz 16-bit mono file.

The library gives me a list of pitches that read ~23kHz. Based on the file the file should not contain anything over 22050 Hz and the spectrum also doesn't show a lot of high-frequency energy.

Is this some sort of bug? Those values are non-sensical as frequency values for a 44.1 kHz file.

**Comment by mavavilj** [comment]
On a second thought, I am now thinking that the file format had something wrong with it. But the format became correct after adding that new tone and exporting.

**Comment by xstreck1** [comment]
It sounds like a mismatch between the sampling frequency of the original file and the specified sampling frequency. If you are using Audacity, I noticed at some point that I had an issue changing the sampling frequency of the file, but that was ~5 years ago, so not sure if that's still the case.

Seems the code works fine though, closing.
