### ISSUE TITLE
Can the VAMP dependencies etc. be removed from the default CMakeLists.txt?

### ISSUE THREAD

**Issue by mavavilj** [xstreck1/LibPyin#14]
I am trying to create as small libraries as possible, and I noticed that the default CMakeLists.txt includes something about VAMP. I don't use VAMP.

I presume that at least lines 9-10 can be removed if VAMP support is not needed:

https://github.com/xstreck1/LibPyin/blob/master/CMakeLists.txt#L9

Right?

It would, possibly, be useful to share a "pyin-only" CMakeLists.txt.

**Comment by xstreck1** [comment]
pYIN itself is developed as VAMP plugin and implements its interfaces, I don't remember all the ins and outs but I don't think it would work without.
