### ISSUE TITLE
Why is this not LGPL?

### ISSUE THREAD

**Issue by mavavilj** [xstreck1/LibPyin#15]
I wanted to use this great library, but I am finding that the GPL license is overly prohibitive, because the main use case for code like this is library use. So if I'd include this into a music app as a plug-in, then it'd require publicizing the whole music app, which I think is unreasonable.

Why isn't it licensed in LGPL?

**Comment by xstreck1** [comment]
Unfortunately this library is only a wrapper to the pYIN source, which itself is licensed under GPL 2 (https://code.soundsoftware.ac.uk/projects/pyin), hence use of LGPL is not permissive>
