### ISSUE TITLE
Where's the libpyin.dll

### ISSUE THREAD

**Issue by lewisallanreed** [xstreck1/LibPyin#2]
In the Unity example section of the readme.md file it says to add the libpyin.dll to the assets but I can't seem to find this .dll file amongst the libpyin library folders I just downloaded from here. Sorry, maybe this is super obvious but I'm a silly newbie.

**Comment by xstreck1** [comment]
Fixed in 17d32510 .

The .dll was filtered out by the .gitignore. Added the x86 version (will work with 32-bit Unity only). Will add 64 bit later.

**Comment by xstreck1** [comment]
Added a 64-bit build to the releases.
