### ISSUE TITLE
DllNotFoundException: LibPyin

### ISSUE THREAD

**Issue by lewisallanreed** [xstreck1/LibPyin#3]
Still the guy who opened the last issue and it's a different thing this time...
First of all, Streck, let me just say your work is great and I appreciate you making such incredible tools available for everyone to use. 

So, since the .dll in your solution is for 32bit, I actually downloaded a Unity archived version with 32bit support (5.6.5f1) and installed it. Running that one, I also 
- allowed unsafe code on MonoDevelop, 
- placed a gmcs.rsp with the command '-unsafe' inside in the project assets folder 
- placed a script on a MainCamera object in a brand new Unity project containing the line 'LoadLibrary.use()'
- moved the LibPyin.dll and LoadLibrary.cs files in the assets folder of my project

BUT -> upon running the code I get the error 

DllNotFoundException: LibPyin
LoadLibrary.use () (at Assets/LoadLibrary.cs:35)

I'm a total noob (as stated in the previous Issue) and I don't want to be pedantic at all, but I really don't know what to do. 
Thanks for any possible replies!! :)

**Comment by xstreck1** [comment]
I made a minimal 5.6.5 project with the .dll, works on my computer, can you test it out please?

[Unity 5.6.5 LibPyin.zip](https://github.com/xstreck1/LibPyin/files/1655352/Unity.5.6.5.LibPyin.zip)

**Comment by lewisallanreed** [comment]
Tested it and, pretty weird but, no. Doesn't work. I don't know if it would give the same problem with anybody else. I'm gonna try building it to see if it's got anything to do with my Unity editor.
