### ISSUE TITLE
Upgrade Wanted

### ISSUE THREAD

**Issue by KittenYang** [xstreck1/LibPyin#6]
Could you please  upgrade to latest [vamp-plugin-sdk](https://code.soundsoftware.ac.uk/projects/vamp-plugin-sdk/repository) and latest [pYIN](https://code.soundsoftware.ac.uk/projects/pyin/repository)? 

Thanks.

**Comment by xstreck1** [comment]
Is there a reason for this? It seems like it works fine as is, so I'd rather keep the working version.
